### ISSUE TITLE
UTF-8 decoding errors

### ISSUE THREAD

**Issue by leonardder** [readthedocs/sphinx-autoapi#169]
I just tried to investigate using AutoAPI for the [NVDA Project](https://nvaccess.org] but unfortunately, the following files seem to cause UnicodeDecodeErrors.

* https://github.com/nvaccess/nvda/blob/master/source/brailleDisplayDrivers/baum.py
* https://github.com/nvaccess/nvda/blob/master/source/brailleDisplayDrivers/freedomScientific.py

I'm also getting the following traceback at some point:

```
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\sphinx\cmd\build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "c:\python37\lib\site-packages\sphinx\application.py", line 268, in __init__
    self._init_builder()
  File "c:\python37\lib\site-packages\sphinx\application.py", line 329, in _init_builder
    self.events.emit('builder-inited')
  File "c:\python37\lib\site-packages\sphinx\events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "c:\python37\lib\site-packages\autoapi\extension.py", line 105, in run_autoapi
    sphinx_mapper_obj.output_rst(root=normalized_root, source_suffix=out_suffix)
  File "c:\python37\lib\site-packages\autoapi\mappers\base.py", line 305, in output_rst
    detail_file.write(rst.encode("utf-8"))
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud800' in position 4708: surrogates not allowed
```
It seems AutoAPI doesn't offer me the information on what file contains surrogate characters.

**Comment by AWhetter** [comment]
I've made a couple of adjustments to how we do unicode handling that should hopefully stop this happening, but it's difficult to know without a reproducible case.
I've also made the default logging print out what file is currently being loaded/parsed/rendered. Turning up the verbosity of the logging will also show which object is currently being rendered.
