### ISSUE TITLE
Building on readthedocs.org: FileNotFoundError: [Errno 2] No such file or directory: '.../docs/source/autoapi/index.rst'

### ISSUE THREAD

**Issue by endrebak** [readthedocs/sphinx-autoapi#190]
Thanks for the great package! It looks like it will be a real timesaver :)

Now onto my question:

I dunno if this is the right place to post this, but I would appreciate help debugging the following error which I get when trying to build my docs with autoapi on readthedocs.org:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyranges/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyranges/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyranges/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 325, in _init_builder
    self.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyranges/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyranges/envs/latest/lib/python3.7/site-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyranges/envs/latest/lib/python3.7/site-packages/autoapi/extension.py", line 132, in run_autoapi
    sphinx_mapper_obj.output_rst(root=normalized_root, source_suffix=out_suffix)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyranges/envs/latest/lib/python3.7/site-packages/autoapi/mappers/base.py", line 308, in output_rst
    self._output_top_rst(root)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyranges/envs/latest/lib/python3.7/site-packages/autoapi/mappers/base.py", line 314, in _output_top_rst
    with open(top_level_index, "wb") as top_level_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/pyranges/checkouts/latest/docs/source/autoapi/index.rst'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyranges/envs/latest/lib/python3.7/site-packages/autoapi/mappers/base.py", line 314, in _output_top_rst
    with open(top_level_index, "wb") as top_level_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/pyranges/checkouts/latest/docs/source/autoapi/index.rst'
The full traceback has been saved in /tmp/sphinx-err-imn1x6t5.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

It complains that no file `.../docs/source/autoapi/index.rst` exists. And it is correct. But for some reason the build works locally. 

Do you have any idea what I need to fix?

Here is my docs folder on the relevant branch: https://github.com/biocore-ntnu/pyranges/tree/docs/docs

**Comment by AWhetter** [comment]
Do you have the conf.py for the documentation?
At the moment it doesn't make the directory for that `top_level_file` variable because it expects it to already exist because that's where the generated documentation has been output already. So the only way that the directory can't exist is if no objects were found to render. Perhaps the `autoapi_dirs` directory is incorrect? It is supposed to be relative to where conf.py exists.

**Comment by endrebak** [comment]
Thanks for the reply :)

I will look into it!
