### ISSUE TITLE
`cannot import name 'l_' from 'sphinx.locale'` when using Go autoapi

### ISSUE THREAD

**Issue by chrisdoherty4** [readthedocs/sphinx-autoapi#211]
When I attempt to use the Go autoapi feature it fails to import some oddly named packages from the `sphinx.locale` pacakage.

```
Running Sphinx v3.0.4
Original exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sphinx/registry.py", line 402, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/sphinxcontrib/golangdomain.py", line 20, in <module>
    from sphinx.locale import l_, _
ImportError: cannot import name 'l_' from 'sphinx.locale' (/usr/local/lib/python3.8/dist-packages/sphinx/locale/__init__.py)


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sphinx/registry.py", line 402, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/sphinxcontrib/golangdomain.py", line 20, in <module>
    from sphinx.locale import l_, _
ImportError: cannot import name 'l_' from 'sphinx.locale' (/usr/local/lib/python3.8/dist-packages/sphinx/locale/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/local/lib/python3.8/dist-packages/sphinx/application.py", line 244, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/registry.py", line 405, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.golangdomain (exception: cannot import name 'l_' from 'sphinx.locale' (/usr/local/lib/python3.8/dist-packages/sphinx/locale/__init__.py))

Extension error:
Could not import extension sphinxcontrib.golangdomain (exception: cannot import name 'l_' from 'sphinx.locale' (/usr/local/lib/python3.8/dist-packages/sphinx/locale/__init__.py))
make: *** [Makefile:35: dirhtml] Error 2
```

Using Python 3.8.2 with the following package versions.

```
Sphinx==3.0.4
sphinx-autoapi==1.3.0
sphinx-autobuild==0.7.1
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-golangdomain==0.2.0.dev0
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-httpdomain==1.7.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-openapi==0.7.0
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
```

**Comment by AWhetter** [comment]
The golangdomain extension doesn't support Sphinx 3. Sphinx 2 works.
I haven't pursued getting the golangdomain extension updated but they would probably accept a patch?

**Comment by chrisdoherty4** [comment]
@AWhetter any hints as to what changed in `sphinx.locale` specifically? I.e. where did this `l_` thing go?

**Comment by AWhetter** [comment]
It was renamed to `_()` in Sphinx 1.8: https://github.com/sphinx-doc/sphinx/commit/8d653a406dc0dc6c2632176ab4757ca15474b10f

**Comment by chrisdoherty4** [comment]
@AWhetter have you got any material on how autoapi works. The existing golangdomain code is quite outdated and doesn't seem to be maintained anymore so I'm looking to write my own for Sphinx 3.x; unless of course you're aware of some other effort?

**Comment by AWhetter** [comment]
golangdomain is completely separate from AutoAPI. It defines the directives that AutoAPI uses, such as `.. go:function::` and `.. go:package::`.
The only documentation for adding a new Domain that I'm aware of is this one: https://www.sphinx-doc.org/en/master/extdev/domainapi.html#domain-api

**Comment by AWhetter** [comment]
I'm guessing that the extension isn't maintained because people tend to use godoc now that it's more stable. I think it's why not many use go in AutoAPI as well. But this is me speculating. I don't actually know why.

**Comment by chrisdoherty4** [comment]
@AWhetter I have the go ahead from my team to sort out the Go support. 

When you said it's a completely separate project I get the impression there's some other way to do this?

Essentially we want autoapi based documentation for Golang extracted code docs. Is that achievable without the domain stuff?

**Comment by AWhetter** [comment]
What I mean is that we don't maintain golangdomain and it isn't specific to AutoAPI.

> Is that achievable without the domain stuff?

No. You need a Sphinx domain to be able to represent the various bit of a language (like functions, attributes, etc) in rst. See https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html
