### ISSUE TITLE
Error reading files when parsing python metaclass

### ISSUE THREAD

**Issue by cassie-ying** [readthedocs/sphinx-autoapi#246]
My autoapi_dir only contains a file :
```
class Meta(type):
    def __init__(self):
        pass
```

And my `conf.py` only contains:
```
extensions = [
    "autoapi.extension",
]
...
```
When I run `sphinx-build sourcedir outdir`, I got an error saying 
```
WARNING: Error reading file
```

**Comment by dektoud** [comment]
Experiencing this as well, here's a traceback with -W enabled:

```
Traceback (most recent call last):
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\mappers\python\mapper.py", line 276, in read_file
    parsed_data = Parser().parse_file(path)
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\mappers\python\parser.py", line 49, in parse_file
    lambda directory: os.path.isfile(os.path.join(directory, "__init__.py")),
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\mappers\python\parser.py", line 44, in _parse_file
    return self.parse(node)
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\mappers\python\parser.py", line 279, in parse
    data = parse_func(node)
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\mappers\python\parser.py", line 267, in parse_module
    child_data = self.parse(child)
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\mappers\python\parser.py", line 279, in parse
    data = parse_func(node)
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\mappers\python\parser.py", line 148, in parse_classdef
    child_data = self.parse(child)
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\mappers\python\parser.py", line 279, in parse
    data = parse_func(node)
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\mappers\python\parser.py", line 109, in parse_classdef
    constructor = node.lookup("__init__")[1]
  File "c:\users\ryanm\rms-python\lib\site-packages\astroid\node_classes.py", line 1063, in lookup
    return self.scope().scope_lookup(self, name)
  File "c:\users\ryanm\rms-python\lib\site-packages\astroid\scoped_nodes.py", line 2191, in scope_lookup
    return frame._scope_lookup(node, name, offset)
  File "c:\users\ryanm\rms-python\lib\site-packages\astroid\scoped_nodes.py", line 190, in _scope_lookup
    stmts = node._filter_stmts(self.locals[name], self, offset)
  File "c:\users\ryanm\rms-python\lib\site-packages\astroid\node_classes.py", line 1151, in _filter_stmts
    if stmt.fromlineno > mylineno > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ryanm\rms-python\lib\site-packages\sphinx\cmd\build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "c:\users\ryanm\rms-python\lib\site-packages\sphinx\application.py", line 278, in __init__
    self._init_builder()
  File "c:\users\ryanm\rms-python\lib\site-packages\sphinx\application.py", line 334, in _init_builder
    self.events.emit('builder-inited')
  File "c:\users\ryanm\rms-python\lib\site-packages\sphinx\events.py", line 99, in emit
    results.append(callback(self.app, *args))
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\extension.py", line 162, in run_autoapi
    patterns=file_patterns, dirs=normalized_dirs, ignore=ignore_patterns
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\mappers\python\mapper.py", line 261, in load
    data = self.read_file(path=path, dir_root=dir_root)
  File "c:\users\ryanm\rms-python\lib\site-packages\autoapi\mappers\python\mapper.py", line 279, in read_file
    LOGGER.warning("Error reading file: {0}".format(path))
  File "c:\users\ryanm\rms-python\lib\logging\__init__.py", line 1734, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "c:\users\ryanm\rms-python\lib\site-packages\sphinx\util\logging.py", line 124, in log
    super().log(level, msg, *args, **kwargs)
  File "c:\users\ryanm\rms-python\lib\logging\__init__.py", line 1766, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "c:\users\ryanm\rms-python\lib\logging\__init__.py", line 1444, in log
    self._log(level, msg, args, **kwargs)
  File "c:\users\ryanm\rms-python\lib\logging\__init__.py", line 1514, in _log
    self.handle(record)
  File "c:\users\ryanm\rms-python\lib\logging\__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "c:\users\ryanm\rms-python\lib\logging\__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "c:\users\ryanm\rms-python\lib\logging\__init__.py", line 890, in handle
    rv = self.filter(record)
  File "c:\users\ryanm\rms-python\lib\logging\__init__.py", line 751, in filter
    result = f.filter(record)
  File "c:\users\ryanm\rms-python\lib\site-packages\sphinx\util\logging.py", line 406, in filter
    raise SphinxWarning(message)
```

**Comment by albert2126** [comment]
I experience the same issue.

    if stmt.fromlineno > mylineno > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

**Comment by ashb** [comment]
I got past this error by changing

https://github.com/readthedocs/sphinx-autoapi/blob/40ebbc965fb7229192925758ea1376a2b7fa24d7/autoapi/mappers/python/parser.py#L135-L136

to

```python
            if base.qname() in ("__builtins__.object", "builtins.object", "builtins.type"):
                continue
```

And that helped for Airflow. Well, helped _a bit_ -- I then hit a "NotImplemetedError" on https://github.com/readthedocs/sphinx-autoapi/blob/40ebbc965fb7229192925758ea1376a2b7fa24d7/autoapi/mappers/python/mapper.py#L166

**Comment by albert2126** [comment]
@ashb,

Thank you for the PR!
I did the same before noticing this solution. Waiting for the package update.
