### ISSUE TITLE
sphinx-autoapi 1.6.0 causing a pickle error

### ISSUE THREAD

**Issue by alanhdu** [readthedocs/sphinx-autoapi#261]
When I tried upgrading sphinx-autoapi from `1.5.1` to `1.6.0`, I started to get a strange pickle error:

```
Exception occurred:
  File "/opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 327, in build
    pickle.dump(self.env, f, pickle.HIGHEST_PROTOCOL)
_pickle.PicklingError: Can't pickle <enum 'Context'>: attribute lookup Context on astroid failed
```

This is with:
- Sphinx 3.4.3
- Python 3.6.10
- Astroid: 2.4.2

The only difference in our build is the upgrade from 1.5.1 to 1.6.0. Unfortunately, I have not been able to figure out how to shrink our internal docs build to get a reproducible minimal example I can share externally. I will try to circle back to this in the next couple of weeks, but it may be a while before I find can extract a minimal example.

<details>
<summary> Full Stacktrace </summary>

```
# Sphinx version: 3.4.3
# Python version: 3.6.10 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.11.2
# Last messages:
#   
#   
#   looking for now-outdated files...
#   
#   none found
#   
#   pickling environment...
#   
#   failed
#   
# Loaded extensions:
#   sphinx.ext.mathjax (3.4.3) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.4.3) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.4.3) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (3.4.3) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.graphviz (3.4.3) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.inheritance_diagram (3.4.3) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/ext/inheritance_diagram.py
#   autoapi.extension (unknown version) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/autoapi/extension.py
#   nbsphinx (0.8.1) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/nbsphinx.py
#   sphinx.ext.intersphinx (3.4.3) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.napoleon (3.4.3) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.viewcode (3.4.3) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/ext/viewcode.py
#   sphinx_rtd_theme (unknown version) from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx_rtd_theme/__init__.py
Traceback (most recent call last):
  File "/opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 298, in build_update
    len(to_build))
  File "/opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 327, in build
    pickle.dump(self.env, f, pickle.HIGHEST_PROTOCOL)
_pickle.PicklingError: Can't pickle <enum 'Context'>: attribute lookup Context on astroid failed
```

</details>

**Comment by adrien-berchet** [comment]
Same here when I try to document this class:
``` python
class TestClass(pd.DataFrame):
    """The test class."""

    def __init__(self, data, *args, **kwargs):
        super().__init__(data, *args, **kwargs)

    @property
    def _constructor(self):
        """Pandas internal constructor property

        See details here:
        https://pandas.pydata.org/pandas-docs/stable/development/extending.html#extending-subclassing-pandas
        """
        return TestClass
```
I join a minimal project to reproduce this:
[sphinx_autoapi_with_pandas.zip](https://github.com/readthedocs/sphinx-autoapi/files/5959742/sphinx_autoapi_with_pandas.zip)

**Comment by ashb** [comment]
@AWhetter Do you have any ideas on this one? I'd currently blocking us from upgrading autoapi in Airflow, so I'd like to fix it, but I'm not having much luck in a quick poke around right now.
