### ISSUE TITLE
RTD build failure during docbuild in mapper

### ISSUE THREAD

**Issue by mhmdkanj** [readthedocs/sphinx-autoapi#324]
Hi,

for some reason, my ReadTheDocs build is failing due to an exception raised in the `mapper.py`.
But I'm not sure what exactly is the problem.
I'm currently using the following
- Python 3.6
- Sphinx 4.4.0
- sphinx-autoapi 1.8.4

I have a usual docs directory tree which includes:
```
docs/
        requirements.txt
        source/
                  conf.py
                  index.rst
```

I'm experiencing the following during the execution of the following command:
`/home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/envs/latest/bin/python -m sphinx -T -b html -d _build/doctrees -D language=en . _build/html`

```
Running Sphinx v4.4.0
loading translations [en]... done
making output directory... done
WARNING: html_static_path entry '_static' does not exist
myst v0.16.1: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/__init__.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/__main__.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/__main__.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/executor/app.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/executor/app.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/executor/executor.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/executor/__init__.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/executor/encoder_decoder.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/handlers/__init__.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/handlers/filetransformation.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/handlers/handlers.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/tests/test_filenamehandler.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/tests/test_filenamehandler.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/tests/__init__.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/tests/test_filelisthandler.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/tests/test_filelisthandler.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/tests/test_executor.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/tests/test_executor.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/tests/test_filetransformation.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/tests/test_filetransformation.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/tests/test_encoder_decoder.py
[AutoAPI] Ignoring /home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/checkouts/latest/renamerename/tests/test_encoder_decoder.py

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/envs/latest/lib/python3.7/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/envs/latest/lib/python3.7/site-packages/autoapi/extension.py", line 165, in run_autoapi
    patterns=file_patterns, dirs=normalised_dirs, ignore=ignore_patterns
  File "/home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/envs/latest/lib/python3.7/site-packages/autoapi/mappers/python/mapper.py", line 289, in load
    if not self._need_to_load(dir_root_files):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/envs/latest/lib/python3.7/site-packages/autoapi/mappers/python/mapper.py", line 259, in _need_to_load
    this_mtime = max(os.path.getmtime(file) for _, file in files)
ValueError: max() arg is an empty sequence

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 322, in _init_builder
    self.events.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/mhmdkanj-renamerename/envs/latest/lib/python3.7/site-packages/sphinx/events.py", line 110, in emit
    (listener.handler, name), exc, modname=modname) from exc
sphinx.errors.ExtensionError: Handler <function run_autoapi at 0x7f86eb1aa3b0> for event 'builder-inited' threw an exception (exception: max() arg is an empty sequence)

Extension error (autoapi.extension):
Handler <function run_autoapi at 0x7f86eb1aa3b0> for event 'builder-inited' threw an exception (exception: max() arg is an empty sequence)

```

**Comment by mhmdkanj** [comment]
Hi @AWhetter , thanks for the fix!
So this actually works locally and docs are built. However on ReadTheDocs, I guess it should fail elegantly with the ExtensionError, right? But why wouldn't it find source fails if they exist under `docs/sources` along with the `conf.py`
