### ISSUE TITLE
1.8.4: sphinx warnings `reference target not found`

### ISSUE THREAD

**Issue by kloczek** [readthedocs/sphinx-autoapi#337]
Fisrst of all it is not possible to use sphinx-build` straight like it use to be.
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/conf.py", line 55, in <module>
    import autoapi
ModuleNotFoundError: No module named 'autoapi'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 345, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/conf.py", line 55, in <module>
    import autoapi
ModuleNotFoundError: No module named 'autoapi'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/conf.py", line 55, in <module>
    import autoapi
ModuleNotFoundError: No module named 'autoapi'
```
That can be fixed with patch like below
```patch
--- a/docs/conf.py~     2022-04-28 10:58:56.000000000 +0000
+++ b/docs/conf.py      2022-04-28 11:00:47.385826932 +0000
@@ -12,6 +12,10 @@
 # All configuration values have a default; values that are commented out
 # serve to show the default.

+import sys
+import os
+sys.path.insert(0, os.path.abspath('..'))
+
 # -- General configuration ------------------------------------------------

 # If your documentation needs a minimal Sphinx version, state it here.
```
That patch does exactly what is mentioned in sphinx copy.py example https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file

Than .. on building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.
Here is the output with warnings:
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0
making output directory... done
WARNING: html_static_path entry '_static' does not exist
[AutoAPI] Reading files... [100%] /home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/autoapi/mappers/python/parser.py
[AutoAPI] Mapping Data... [100%] /home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/autoapi/mappers/python/parser.py
[autosummary] generating autosummary for: how_to.rst, index.rst, maintenance/design.rst, maintenance/release-process.rst, reference/config.rst, reference/directives.rst, reference/templates.rst, tutorials.rst
loading intersphinx inventory from https://jinja.palletsprojects.com/en/3.0.x/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 8 added, 0 changed, 0 removed
reading sources... [100%] tutorials
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-sphinx-autoapi.3 { tutorials how_to reference/config reference/directives reference/templates maintenance/design maintenance/release-process } /home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/how_to.rst:107: WARNING: py:mod reference target not found: sphinx
/home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/how_to.rst:107: WARNING: py:mod reference target not found: sphinx.ext.autodoc.typehints
/home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/how_to.rst:136: WARNING: py:mod reference target not found: sphinx.ext.autodoc.typehints
/home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/reference/directives.rst:66: WARNING: py:class reference target not found: autoapi.mappers.base.PythonMapperBase
/home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/reference/templates.rst:49: WARNING: 'confval' reference target not found: autoapi_include_summaries
/home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/reference/templates.rst:51: WARNING: py:class reference target not found: PythonMapperBase
/home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/reference/templates.rst:52: WARNING: py:attr reference target not found: sphinx.version_info
docstring of autoapi.mappers.dotnet.DotNetPythonMapper:: WARNING: py:class reference target not found: list of dict objects
/home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/maintenance/design.rst:30: WARNING: py:meth reference target not found: type.__init__
/home/tkloczko/rpmbuild/BUILD/sphinx-autoapi-1.8.4/docs/maintenance/design.rst:31: WARNING: py:meth reference target not found: type.__new__
done
build succeeded, 11 warnings.
```

**Comment by AWhetter** [comment]
Building the documentation like this isn't supported. You should use `tox -e docs`, or emulate what tox is doing by making your own virtualenv and running the same commands that tox does.

**Comment by kloczek** [comment]
Gentle ping .. did you try to use `-n` option? 🤔 
\(does't matter with tox or not)
